POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Desenvolvimento"
}

### 

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/category/e993d1cf-2850-4bc5-ade5-78e4a06e660b HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Ana",
    "description": "Curso de Java",
    "price": 100.00,
    "category_id": "e993d1cf-2850-4bc5-ade5-78e4a06e660b",
    "image_url": "http://www.google.com.br" 
}